Repository mohdfawad99/hacktoberfest-2021, pull requests merged in 2021-10, with the labels that each got.

#12 js code added
  JavaScript Programs/reverse-string.js
  JavaScript Programs/star-pattern.js
Labels: hacktoberfest-accepted

#18 Bubble Sort
  Python Programs/bubble_sort.py
Labels: hacktoberfest-accepted

#19 Merge Sort
  Python Programs/merge_sort.py
Labels: hacktoberfest-accepted

#21 Selection Sort
  Python Programs/selection_sort.py
Labels: hacktoberfest-accepted

#20 Insertion Sort
  Python Programs/insertion_sort.py
Labels: hacktoberfest-accepted

#15 Create Selection Sort
  Java Programs/SelectionSort.java
Labels: hacktoberfest-accepted

#17 Java Linear Search Program
  Java Programs/LinearSearch.java
Labels: hacktoberfest-accepted

#22 Palindrome.py
  Python Programs/palindrome.py
Labels: hacktoberfest-accepted

#23 Count houses
  C++ Programs/Allocation_of_house.cpp
Labels: hacktoberfest-accepted

#24 MergeSort
  Java Programs/MergeSort.java
Labels: hacktoberfest-accepted

#27 Create EmployeeProgram.java
  Java Programs/EmployeeProgram.java
Labels: help wanted, hacktoberfest-accepted

#28 Bubble Sort
  Java Programs/BubbleSort.java
Labels: hacktoberfest-accepted

#29 Factorial using recursion - (with correction)
  Python Programs/factorial_recursion.py
Labels: hacktoberfest-accepted

#30 Modified SumOfDigit.java
  Java Programs/SumOfDigits.java
Labels: hacktoberfest-accepted

#33 bubble_sort
  C Programs/bubble_sort.c
Labels: hacktoberfest-accepted

#34 Fibonacci series
  C Programs/fibonacci_series.c
Labels: hacktoberfest-accepted

#35 Factorial of a number
  C Programs/factorial_of_number.c
Labels: hacktoberfest-accepted

#37 Check Leap Year
  C Programs/check_leap_year.c
Labels: hacktoberfest-accepted

#36 Create QuickSort.java
  Java Programs/QuickSort.java
Labels: hacktoberfest-accepted

#38 Created Armstrong_number.cpp
  C++ Programs/Armstrong_number.cpp
Labels: hacktoberfest-accepted

#40 Create complex-numbers-addition.cpp
  C++ Programs/complex-numbers-addition.cpp
Labels: hacktoberfest-accepted

#42 Add MergeSortNatural
  Java Programs/MergeSortNatural.java
Labels: hacktoberfest-accepted

#45 js two file added
  JavaScript Programs/find-factorial.js
  JavaScript Programs/multiplication-table.js
Labels: hacktoberfest-accepted

#46 Added Radix Sort
  Python Programs/radix_sort.py
Labels: hacktoberfest-accepted

#48 Added Ford-Fulkerson Algorithm in java
  Java Programs/FordFulkerson.java
Labels: hacktoberfest-accepted

#49 PascalCase converter method in javascript
  JavaScript Programs/pascal-case.js
Labels: hacktoberfest-accepted

#50 Changed class name.
  Java Programs/Fascinating.java
Labels: hacktoberfest-accepted

#51 Sorting Algorithms
  Java Programs/Sort.java
Labels: hacktoberfest-accepted

#52 Binary Search
  Java Programs/BinarySearch.java
Labels: hacktoberfest-accepted

#57 Codeforces Problem added
  Codeforces Problems/A_Eshag_Loves_Big_Arrays.cpp
Labels: hacktoberfest-accepted

#59 Delete New Text Document.txt
  ML-DS-AI Projects/New Text Document.txt
Labels: hacktoberfest-accepted

#63 Determining Compressive Strength of Concrete
  ML-DS-AI Projects/compressive_strength_concrete.ipynb
Labels: hacktoberfest-accepted

#64 Determining Compressive Strength of Concrete
  ML-DS-AI Projects/compressive_strength_concrete.ipynb
Labels: hacktoberfest-accepted

#67 Delete compressive_strength_concrete.ipynb
  ML-DS-AI Projects/compressive_strength_concrete.ipynb
Labels: hacktoberfest-accepted

#68 Determining Compressive Strength of Concrete
  ML-DS-AI Projects/compressive_strength_concrete.ipynb
Labels: hacktoberfest-accepted

#55 Tower Of Hanoi problem using java language (Recursion) . #Hacktoberfest2021
  Java Programs/TowerOfHanoi.java
Labels: hacktoberfest-accepted

#60 Average Calculator
  JavaScript Programs/calc-avg.js
Labels: hacktoberfest-accepted

#61 Create Cyclic_Prime.java
  Cyclic_Prime.java
Labels: hacktoberfest-accepted

#62 Factorial
  Java Programs/Factorial.java
Labels: hacktoberfest-accepted

#65 Add Neighbourhood Graph Program
  C Programs/neighbourhood_graph.c
Labels: hacktoberfest-accepted

#69 Added BucketSort Algorithm
  Java Programs/BucketSort.java
  Java Programs/HeapSort.java
Labels: good first issue, hacktoberfest-accepted

#70 Largest_Smallest Numbers
  Java Programs/LargestSmallest.java
Labels: good first issue, hacktoberfest-accepted

#71 Update Expression.java
  Java Programs/Expression.java
Labels: hacktoberfest-accepted

#73 added a bubble sort sorting method written in C++ language
  bubblesort.cpp
Labels: good first issue, hacktoberfest-accepted

#72 C++ Programs On DSA
  C++ Programs/2darray.cpp
  C++ Programs/Rotatearray8.cpp
  C++ Programs/StrongNeighbour6.cpp
  C++ Programs/equilibriumindex13.cpp
  C++ Programs/frequency12.cpp
  C++ Programs/inserend.cpp
  C++ Programs/insertanypos.cpp
  C++ Programs/insertatend1.cpp
  C++ Programs/insertatindex2.cpp
  C++ Programs/majorityelement4.cpp
  C++ Programs/max2max.cpp
  C++ Programs/max2max5.cpp
  C++ Programs/maxoccint10.cpp
  C++ Programs/meanmedian3.cpp
  C++ Programs/reversearraygroups7.cpp
  C++ Programs/waveform11.cpp
Labels: hacktoberfest-accepted

#74 Added program for element that appears once
  C++ Programs/Element That Appears once.cpp
Labels: hacktoberfest-accepted

#75 Binary Indexed Tree Implementation in Python
  Python Programs/Binary_indexed_tree.py
Labels: hacktoberfest-accepted

#77 Added code to reverse sentence using recursion
  C Programs/stringReverse.c
Labels: hacktoberfest-accepted

#78 Tower_of_hanoi
  Java Programs/Tower_of_hanoi.java
Labels: hacktoberfest-accepted

#79 Added C program for insertion sort with time analysis
  C Programs/insertionSort.c
Labels: hacktoberfest-accepted

#80 cf A problems with proper file extension and problem link
  Codeforces Problems/Ezzat_and_Two_Subsequences.cpp
  Codeforces Problems/Gregor_and_Cryptography.cpp
  Codeforces Problems/TheMiracle_and_theSleeper.cpp
  Codeforces Problems/sum_of_dissatisfaction.cpp
Labels: hacktoberfest-accepted

#81 Added a C Program for Knapsack problem
  C Programs/Knapsack.c
Labels: hacktoberfest-accepted

#82 Segment Tree Implementation in Python
  Python Programs/Segment_tree.py
Labels: hacktoberfest-accepted

#83 Leaders in an array
  C++ Programs/Leaders in a array.cpp
Labels: hacktoberfest-accepted

#85 Binary Search Tree Implementation In Python
  Python Programs/Binary_Search_Tree.py
Labels: hacktoberfest-accepted

#87 Added Java, C++ and Codeforces programs.
  C++ Programs/BigNum_Sum.cpp
  Codeforces Problems/Double_Matrix.cpp
  Codeforces Problems/Rebus.cpp
  Java Programs/Binary2Decimal.java
  Java Programs/Decimal2Binary.java
Labels: hacktoberfest-accepted

#88 Added Collatz Iterator
  Python Programs/Collatz Iterator.py
Labels: hacktoberfest-accepted

#89 Create date.js
  JavaScript Programs/date.js
Labels: hacktoberfest-accepted

#90 Linked List in Python
  Python Programs/Linked_List.py
Labels: hacktoberfest-accepted

#96 Triangle Star Pattern
  Python Programs/triangle_star_pattern.py
Labels: hacktoberfest-accepted

#91 Updated class name and file name to StringPalindrome
  Java Programs/StringPalindrome.java
Labels: hacktoberfest-accepted
